services:
  - type: web
    name: nordic-runes-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3003
      - key: NODE_ENV
        value: production
