// Vietnamese Rune Translations
export const RUNES_VI = [
  { id: 1, name: "Fehu", symbol: "ᚠ", meaning: "Gia súc, tài sản, dồi dào", reversed: "Mất mát, nghèo đói, tham lam", description: "Fehu đại diện cho thịnh vượng vật chất, giàu có và dồi dào. Nó được liên kết với sinh sản, tăng trưởng và tích lũy tài nguyên. Trong đọc vị, nó thường chỉ ra lợi nhuận tài chính, thành công hoặc sự hiện thực hóa của sự dồi dào vào cuộc sống của bạn.", reversed_description: "Khi Fehu xuất hiện đảo ngược, mất mát tài chính hoặc sự thiếu hụt có thể có mặt. Rune này cảnh báo về tài nguyên cạn kiệt, tư duy nghèo đói hoặc tham lam mà không có sự khôn ngoan. Nó gọi bạn kiểm tra mối quan hệ của bạn với an ninh tài chính và tìm sự cân bằng.", upright_guidance: "Tài sản chảy vào - Thịnh vượng hiện diện hoặc sắp tới. Gia súc - Nuôi dưỡng tài sản của bạn. Dồi dào - Bạn có những gì bạn cần.", reversed_guidance: "Mất tài nguyên - Theo dõi tài chính cẩn thận. Tư duy nghèo đói - Tư duy sự thiếu hụt chặn dòng chảy. Tham lam - Dục vọng mà không có sự khôn ngoan tạo ra khổ đau." },
  { id: 2, name: "Uruz", symbol: "ᚢ", meaning: "Sức mạnh, bò rừng, quyền lực", reversed: "Yếu đuối, mất kiểm soát", description: "Uruz mang đủ sức mạnh thô, quyền lực nguyên thủy và năng lượng sống. Nó đại diện cho sức mạnh thể chất, can đảm và các lực lượng hoang dã của thiên nhiên. Rune này thường chỉ ra một thời gian của sức mạnh, quyết tâm và khả năng vượt qua những trở ngại qua ý chí thuần túy.", reversed_description: "Khi Uruz xuất hiện đảo ngược, sức mạnh giảm đi và kiểm soát có thể trượt đi. Rune này gợi ý kiệt sức, dễ bị tổn thương hoặc mất hướng. Nó gọi bạn nghỉ ngơi, phục hồi và tái tạo lại các nguồn lực của bạn trước khi tiếp tục.", upright_guidance: "Sức mạnh có sẵn - Quyền lực của bạn ở đỉnh. Bò rừng - Khai thác năng lượng chưa được sử dụng. Can đảm - Hành động táo bạo ngay bây giờ.", reversed_guidance: "Yếu đuối xuất hiện - Kiểm soát tốc độ. Mất kiểm soát - Tái giành lại trung tâm. Kiệt sức - Cần nghỉ ngơi." },
  { id: 3, name: "Thurisaz", symbol: "ᚦ", meaning: "Thor, bảo vệ, thách thức", reversed: "Nguy hiểm, dễ bị tổn thương", description: "Thurisaz là rune của Thor, vị thần sét, biểu tượng bảo vệ, xung đột và thách thức. Nó đại diện cho các trở ngại phải đối mặt và vượt qua. Rune này thường xuất hiện khi bạn phải đối mặt với những thách thức đòi hỏi sức mạnh và quyết tâm để vượt qua.", reversed_description: "Khi Thurisaz xuất hiện đảo ngược, các phòng vệ bị suy yếu và nguy hiểm có thể gần. Rune này cảnh báo về dễ bị tổn thương, xung đột chưa được giải quyết hoặc đe dọa đến an toàn của bạn. Nó thúc đẩy cần thận trọng và nhu cầu tăng cường ranh giới bảo vệ của bạn.", upright_guidance: "Bảo vệ của Thor - Phòng vệ mạnh mẽ. Thách thức phía trước - Tăng trưởng thông qua đấu tranh. Xung đột - Đứng vững.", reversed_guidance: "Dễ bị tổn thương bộc lộ - Tăng cường phòng vệ. Nguy hiểm hiện tại - Khuyên canh cánh. Xung đột chưa được giải quyết - Tìm kiếm hòa bình." },
  { id: 4, name: "Ansuz", symbol: "ᚨ", meaning: "Thần, giao tiếp, sự khôn ngoan", reversed: "Giao tiếp sai lệch, nhầm lẫn", description: "Ansuz đại diện cho sự khôn ngoan thánh linh, giao tiếp và sức mạnh của lời nói. Nó được liên kết với Odin và quà tặng của kiến thức. Rune này thường chỉ ra giao tiếp rõ ràng, cảm hứng, thông điệp và tầm quan trọng của việc lắng nghe sự khôn ngoan nội tâm của bạn.", reversed_description: "Khi Ansuz xuất hiện đảo ngược, giao tiếp bị phá vỡ và nhầm lẫn thống trị. Rune này gợi ý hiểu lầm, thông điệp ẩn giấu hoặc mất sự rõ ràng. Nó gọi bạn tìm kiếm sự làm rõ và lắng nghe cẩn thận hơn trước khi hành động.", upright_guidance: "Giao tiếp rõ ràng - Nói lên sự thật của bạn. Sự khôn ngoan chảy - Tin tưởng trực giác. Thông điệp đến - Nghe lắng cẩn thận.", reversed_guidance: "Giao tiếp sai lệch - Làm rõ ý định. Nhầm lẫn thống trị - Tìm kiếm sự hiểu biết. Im lặng - Nói lên." },
  { id: 5, name: "Raido", symbol: "ᚱ", meaning: "Cuộc hành trình, du lịch, bánh xe", reversed: "Trễ, hấp tấp", description: "Raido biểu tượng cho các cuộc hành trình, cả vật lý lẫn tâm linh. Nó đại diện cho chuyển động, chu kỳ và hành trình của cuộc sống. Rune này thường chỉ ra du lịch, chuyển đổi hoặc nhu cầu thay đổi quan điểm của bạn để tiến lên phía trước.", reversed_description: "Khi Raido xuất hiện đảo ngược, chuyển động bị chặn hoặc trễ. Rune này cảnh báo về các chướng ngại trên con đường của bạn, thời gian kém hoặc hành động vội vàng mà không có lập kế hoạch thích hợp. Nó gọi bạn dừng lại, đánh giá lại hướng của bạn và chờ đúng thời điểm.", upright_guidance: "Cuộc hành trình bắt đầu - Chuyển động thuận lợi. Du lịch - Sự thông qua an toàn phía trước. Chu kỳ quay - Tiến độ triển khai.", reversed_guidance: "Trễ không thể tránh - Kiên nhẫn yêu cầu. Hấp tấp - Chậm lại. Cuộc hành trình bị chặn - Đánh giá lại hướng." },
  { id: 6, name: "Kenaz", symbol: "ᚲ", meaning: "Đuốc, ánh sáng, kiến thức", reversed: "Sự thiếu hiểu biết, bóng tối", description: "Kenaz là rune của sự chiếu sáng, đại diện cho ánh sáng, kiến thức và sự hiểu biết. Nó biểu tượng cho sự rõ ràng, cái nhìn sâu sắc và sự bộc lộ những sự thật ẩn giấu. Rune này thường chỉ ra rằng các câu trả lời đang trở nên rõ ràng hoặc sự hiểu biết sẽ sớm đến.", reversed_description: "Khi Kenaz xuất hiện đảo ngược, bóng tối che khuất sự thật và nhầm lẫn thịnh hành. Rune này cảnh báo về kiến thức ẩn giấu, thông tin được giữ kín hoặc sự thiếu hiểu biết về các sự kiện quan trọng. Nó gọi bạn tìm kiếm câu trả lời và chiếu sáng những gì đã bị ẩn giấu.", upright_guidance: "Đuốc thắp - Sự rõ ràng sắp tới. Ánh sáng bộc lộ - Sự thật nổi lên. Kiến thức - Sự hiểu biết phát triển.", reversed_guidance: "Bóng tối - Nhầm lẫn thành thạo. Sự thiếu hiểu biết - Tìm kiếm câu trả lời. Che khuất - Sự thật ẩn giấu." },
  { id: 7, name: "Gebo", symbol: "ᚳ", meaning: "Quà tặng, hợp tác, cân bằng", reversed: "Nợ, mất cân bằng", description: "Gebo đại diện cho quà tặng, trao đổi và hợp tác. Nó biểu tượng cho sự cân bằng, tương hỗ và kết nối giữa tất cả mọi thứ. Rune này thường chỉ ra mối quan hệ hài hòa, trao đổi công bằng hoặc nhu cầu duy trì sự cân bằng trong cuộc sống của bạn.", reversed_description: "Khi Gebo xuất hiện đảo ngược, sự cân bằng bị mất và nợ tích tụ. Rune này cảnh báo về mối quan hệ mất cân bằng, các nghĩa vụ nặng nề hoặc trao đổi không công bằng. Nó gọi bạn khôi phục sự cân bằng và giải quyết những gì chưa được giải quyết.", upright_guidance: "Quà tặng nhận - Sự hào phóng chảy. Hợp tác - Cân bằng được tôn trọng. Trao đổi - Thương mại công bằng.", reversed_guidance: "Nợ phải trả - Nghĩa vụ nặng. Mất cân bằng - Khôi phục sự cân bằng. Xung đột - Hòa giải." },
  { id: 8, name: "Wunjo", symbol: "ᚹ", meaning: "Vui vẻ, hài hòa, ánh sáng", reversed: "Buồn, bất hòa", description: "Wunjo hiện thân hóa vui vẻ, hạnh phúc và hài hòa. Nó đại diện cho sự hài lòng, ánh sáng và thỏa mãn những mong muốn. Rune này thường chỉ ra kết quả tích cực, hạnh phúc và đạt được các mục tiêu mang lại sự thỏa mãn thực sự.", reversed_description: "Khi Wunjo xuất hiện đảo ngược, vui vẻ phai mờ và bất hòa thay thế hài hòa. Rune này gợi ý buồn bã, xung đột hoặc mất mát điều gì đó quý giá. Nó gọi bạn tìm kiếm hỗ trợ và vượt qua nỗi buồn trước khi ánh sáng trở lại.", upright_guidance: "Vui vẻ dồi dào - Ăn mừng. Hài hòa - Hòa bình thịnh hành. Ánh sáng - Độ sáng trở lại.", reversed_guidance: "Buồn hiện tại - Nỗi buồn công nhân. Bất hòa - Xung đột chữa lành. Buồn bã - Tìm kiếm hỗ trợ." },
  { id: 9, name: "Hagalaz", symbol: "ᚼ", meaning: "Mưa đá, gián đoạn, chuyển đổi", reversed: "Hỗn loạn, hủy diệt", description: "Hagalaz đại diện cho mưa đá, gián đoạn đột ngột và các lực lượng chuyển đổi. Nó biểu tượng cho những thách thức bắt đầu thay đổi và tăng trưởng. Rune này thường chỉ ra sự hỗn loạn, nhưng cuối cùng là chuyển đổi và đổi mới dẫn đến kết quả tích cực.", reversed_description: "Khi Hagalaz xuất hiện đảo ngược, hỗn loạn hủy diệt đe dọa sự ổn định. Rune này cảnh báo về mất kiểm soát, gián đoạn nghiêm trọng hoặc các lực lượng ngoài tầm kiểm soát của bạn. Nó gọi bạn tìm kiếm nơi trú ẩn, ổn định tình huống của bạn và bảo vệ những gì quan trọng nhất.", upright_guidance: "Mưa đá rơi - Gián đoạn mang lại thay đổi. Chuyển đổi - Tái sinh sắp tới. Thách thức - Tăng trưởng thông qua đấu tranh.", reversed_guidance: "Hỗn loạn thành thạo - Tìm sự ổn định. Hủy diệt - Ngăn chặn tổn thất tiếp theo. Bão - Tìm kiếm nơi trú ẩn." },
  { id: 10, name: "Nauthiz", symbol: "ᚾ", meaning: "Nhu cầu, tất yếu, ma sát", reversed: "Ràng buộc, khó khăn", description: "Nauthiz đại diện cho nhu cầu, ràng buộc và ma sát thúc đẩy thay đổi. Nó biểu tượng cho khó khăn dạy những bài học quý giá. Rune này thường chỉ ra những hạn chế thực sự giúp tăng cường tính cách và quyết tâm của bạn.", reversed_description: "Khi Nauthiz xuất hiện đảo ngược, khó khăn sâu hơn và ràng buộc cảm thấy không thể thoát khỏi. Rune này cảnh báo về những hạn chế nghiêm trọng, khổ đau mà không có sự tăng trưởng hoặc bị mắc kẹt. Nó gọi bạn tìm kiếm giúp đỡ, đánh giá lại tình huống của bạn và tìm cách tiến lên.", upright_guidance: "Nhu cầu cảm thấy - Động lực xây dựng. Ma sát - Áp lực tạo ra thay đổi. Tất yếu - Tăng trưởng thiết yếu.", reversed_guidance: "Ràng buộc cảm thấy - Hạn chế thực sự. Khó khăn - Kiên trì. Đấu tranh - Tìm kiếm giúp đỡ." },
  { id: 11, name: "Isa", symbol: "ᚣ", meaning: "Băng, tĩnh lặng, tạm dừng", reversed: "Tình trạng đông cứng, tình huống bị đông cứng", description: "Isa đại diện cho băng, tĩnh lặng và tạm dừng. Nó biểu tượng cho một khoảng thời gian chờ đợi, suy ngẫm và sự làm rõ đến từ tĩnh lặng. Rune này thường chỉ ra một thời gian để giữ vững, suy ngẫm về tình huống của bạn và duy trì tiêu điểm của bạn.", reversed_description: "Khi Isa xuất hiện đảo ngược, tình trạng đông cứng đã xảy ra và tiến độ bị đông cứng. Rune này cảnh báo về bị mắc kẹt, không thể tiến lên hoặc tĩnh lặng không có sự sống. Nó gọi bạn phá vỡ băng, khởi động chuyển động và rã đông những gì đã bị đông cứng.", upright_guidance: "Băng giữ vững - Tạm dừng cần thiết. Tĩnh lặng - Sự rõ ràng nổi lên. Suy ngẫm - Hiểu sâu.", reversed_guidance: "Tình trạng đông cứng - Chuyển động bị chặn. Đông cứng - Cần rã đông. Tĩnh lặng - Trở nên không có sự sống." },
  { id: 12, name: "Jera", symbol: "ᚤ", meaning: "Năm, mùa vụ, chu kỳ", reversed: "Trễ, chu kỳ bị phá vỡ", description: "Jera biểu tượng cho chu kỳ các mùa, mùa vụ và nhịp độ tự nhiên. Nó đại diện cho hoàn thành, phần thưởng cho nỗ lực và sự quay vòng của năm. Rune này thường chỉ ra hoàn thành thành công của các chu kỳ, mùa vụ những gì bạn đã gieo và tiến triển tự nhiên.", reversed_description: "Khi Jera xuất hiện đảo ngược, chu kỳ bị phá vỡ và mùa vụ bị trễ. Rune này cảnh báo rằng các nỗ lực có thể không mang lại kết quả như dự kiến hoặc tiến trình tự nhiên bị gián đoạn. Nó gọi bạn kiên nhẫn, tin tưởng thời gian và tiếp tục công việc của bạn.", upright_guidance: "Mùa vụ đến - Kết quả hiện rõ. Chu kỳ hoàn thành - Bắt đầu mới. Phần thưởng kiếm được - Lễ kỷ niệm.", reversed_guidance: "Trễ - Kiên nhẫn cần thiết. Chu kỳ bị phá vỡ - Khởi động lại. Mùa vụ bị giữ lại - Tiếp tục cố gắng." },
  { id: 13, name: "Eihwaz", symbol: "ᚥ", meaning: "Cây Yew, bảo vệ, chết/tái sinh", reversed: "Không đáng tin, tình trạng đông cứng", description: "Eihwaz là rune của cây Yew, đại diện cho bảo vệ, chuyển đổi và chu kỳ chết và tái sinh. Nó biểu tượng cho sức chịu đựng và khả năng thích ứng. Rune này thường chỉ ra các ảnh hưởng bảo vệ hoặc một thời gian chuyển đổi cá nhân và đổi mới.", reversed_description: "Khi Eihwaz xuất hiện đảo ngược, bảo vệ thất bại và đổi mới bị chặn. Rune này cảnh báo về hỗ trợ không đáng tin, tình trạng đông cứng thay vì chuyển đổi hoặc không thể thích ứng. Nó gọi bạn tái xây dựng phòng vệ và tìm kiếm các nguồn ổn định mới.", upright_guidance: "Cây Yew mạnh - Bảo vệ vững chắc. Chết/tái sinh - Chuyển đổi thánh linh. Sức chịu đựng - Thích ứng và phát triển.", reversed_guidance: "Không đáng tin - Lòng tin bị phá vỡ. Tình trạng đông cứng - Đổi mới bị chặn. Bảo vệ thất bại - Tái xây dựng phòng vệ." },
  { id: 14, name: "Perthro", symbol: "ᚦ", meaning: "Vận mệnh, bí ẩn, khởi đầu", reversed: "Xui xẻo, lừa dối", description: "Perthro đại diện cho vận mệnh, bí ẩn và khởi đầu. Nó biểu tượng cho cái chưa biết, kiến thức ẩn giấu và những bí mật của cuộc sống. Rune này thường chỉ ra rằng những bí ẩn đang được bộc lộ, khởi đầu vào kiến thức mới hoặc nhu cầu chấp nhận cái chưa biết.", reversed_description: "Khi Perthro xuất hiện đảo ngược, lừa dối che khuất sự thật và xui xẻo hiện đen mây. Rune này cảnh báo về những nguy hiểm ẩn giấu, thông tin sai lệch hoặc vận mệnh hoạt động chống lại bạn. Nó gọi bạn cảnh giác, tin tưởng trực giác của bạn và tìm kiếm sự làm rõ.", upright_guidance: "Bí ẩn bộc lộ - Bí mật nổi lên. Khởi đầu - Kiến thức mới bắt đầu. Vận mệnh - Định mệnh triển khai.", reversed_guidance: "Xui xẻo - Xui xẻo rõ ràng. Lừa dối - Sự thật ẩn giấu. Bí ẩn - Vẫn mờ nhạt." },
  { id: 15, name: "Algiz", symbol: "ᚨ", meaning: "Bảo vệ, phòng vệ, khiên", reversed: "Dễ bị tổn thương, nguy hiểm", description: "Algiz đại diện cho bảo vệ, phòng vệ và khiên nâng lên của chiến binh. Nó biểu tượng cho an toàn, bảo vệ và ý thức cao hơn. Rune này thường chỉ ra rằng bạn được bảo vệ, các lực lượng tâm linh đang hướng dẫn bạn hoặc bảo vệ có sẵn cho bạn.", reversed_description: "Khi Algiz xuất hiện đảo ngược, các khiên bảo vệ của bạn yếu đi và dễ bị tổn thương tăng lên. Rune này cảnh báo về phơi bày nguy hiểm, phòng vệ suy yếu hoặc mất bảo vệ tâm linh. Nó gọi bạn tăng cường ranh giới của bạn và tìm kiếm an toàn.", upright_guidance: "Khiên nâng cao - Bảo vệ mạnh mẽ. Phòng vệ sẵn - An toàn được đảm bảo. Quyền lực cao hơn - Hướng dẫn bạn.", reversed_guidance: "Dễ bị tổn thương - Canh gác hạ. Nguy hiểm - Cảnh báo cảnh. Không được bảo vệ - Tăng cường ranh giới." },
  { id: 16, name: "Sowilo", symbol: "ᚳ", meaning: "Mặt trời, thành công, toàn bộ", reversed: "Thất bại, thiếu năng lượng", description: "Sowilo là rune của mặt trời, đại diện cho thành công, toàn bộ và sự rõ ràng. Nó biểu tượng cho sức sống, năng lượng và chiến thắng của ánh sáng trên bóng tối. Rune này thường chỉ ra thành công, thành tựu và một giai đoạn rõ ràng và động lực tích cực.", reversed_description: "Khi Sowilo xuất hiện đảo ngược, bóng tối che khuất con đường của bạn và năng lượng phai mờ. Rune này cảnh báo về thất bại, kiệt sức hoặc sự mờ nhạt của hy vọng. Nó gọi bạn nghỉ ngơi, xây dựng lại sức mạnh của bạn và chờ ánh sáng trở lại.", upright_guidance: "Mặt trời tỏa sáng - Thành công rõ ràng. Toàn bộ - Tích hợp hoàn tất. Năng lượng - Sức sống chảy.", reversed_guidance: "Thất bại - Nỗ lực dừng lại. Năng lượng thấp - Kiệt sức thực. Bóng tối - Ánh sáng mờ nhạt." },
  { id: 17, name: "Tiwaz", symbol: "ᛏ", meaning: "Tyr, can đảm, chiến thắng", reversed: "Thất bại, sợ hãi", description: "Tiwaz là rune của Tyr, vị thần chiến binh, đại diện cho can đảm, chiến thắng và quyền lực nam tính. Nó biểu tượng cho danh dự, công lý và tinh thần chiến binh. Rune này thường chỉ ra chiến thắng, nhu cầu bảo vệ các niềm tin của bạn hoặc sự tiếp cận của chiến thắng.", reversed_description: "Khi Tiwaz xuất hiện đảo ngược, can đảm lung lay và thất bại tiếp cận. Rune này cảnh báo về tổn thất, bất công hoặc nhu cầu rút lui và đánh giá lại. Nó gọi bạn tôn trọng các giới hạn của bạn và tìm kiếm chiến lược mới.", upright_guidance: "Can đảm tăng - Hành động táo bạo. Chiến thắng gần - Chiến thắng sắp tới. Danh dự - Đứng cao.", reversed_guidance: "Thất bại hiện ra - Chấp nhận mất mát. Sợ hãi - Sợ hãi thống trị. Công lý - Từ chối." },
  { id: 18, name: "Berkano", symbol: "ᛒ", meaning: "Cây dương, tăng trưởng, sinh sản", reversed: "Tình trạng đông cứng, vô sinh", description: "Berkano đại diện cho cây dương, biểu tượng cho tăng trưởng, sinh sản và khởi đầu mới. Nó đại diện cho nuôi dưỡng, mẹ và nguyên tắc nữ. Rune này thường chỉ ra tăng trưởng, các dự án mới phát triển hoặc một giai đoạn sinh sản và dồi dào.", reversed_description: "Khi Berkano xuất hiện đảo ngược, tăng trưởng dừng lại và sinh sản giảm đi. Rune này cảnh báo về vô sinh, các chướng ngại chặn tiến bộ hoặc các dự án đình trệ. Nó gọi bạn loại bỏ các rào cản và nuôi dưỡng những gì bị chặn.", upright_guidance: "Cây dương phát triển - Bắt đầu mới. Sinh sản - Dồi dào chảy. Tăng trưởng - Nuôi dưỡng nó.", reversed_guidance: "Tình trạng đông cứng - Tăng trưởng tạm dừng. Vô sinh - Cảm thấy vô sinh. Bị chặn - Loại bỏ chướng ngại." },
  { id: 19, name: "Ehwaz", symbol: "ᛖ", meaning: "Ngựa, chuyển động, hợp tác", reversed: "Tình trạng đông cứng, xung đột", description: "Ehwaz đại diện cho ngựa, biểu tượng cho chuyển động, hợp tác và hài hòa. Nó đại diện cho kỷ nguyên trung thành và hành động đồng bộ. Rune này thường chỉ ra hợp tác, tiến bộ suôn sẻ hoặc nhu cầu tiến lên phía trước với các cộng sự đáng tin.", reversed_description: "Khi Ehwaz xuất hiện đảo ngược, chuyển động tạm dừng và hợp tác căng thẳng. Rune này cảnh báo về xung đột trong mối quan hệ, không thể tiến lên cùng nhau hoặc mất sự đồng bộ. Nó gọi bạn giải quyết bất hòa và tái xây dựng lòng tin.", upright_guidance: "Ngựa di chuyển - Tiến bộ chảy. Hợp tác - Hài hòa xếp hàng. Lòng trung thành - Lòng tin được tôn trọng.", reversed_guidance: "Tình trạng đông cứng - Tiến bộ bị chặn. Xung đột - Hợp tác căng thẳng. Chuyển động - Tạm dừng." },
  { id: 20, name: "Mannaz", symbol: "ᛘ", meaning: "Con người, bản thân, tình trạng con người", reversed: "Tự lợi, yếu đuối", description: "Mannaz đại diện cho nhân loại, bản thân và sự phụ thuộc lẫn nhau. Nó biểu tượng cho lý trí, trí tuệ và tiềm năng con người. Rune này thường chỉ ra tự nhận thức, tầm quan trọng của cộng đồng hoặc suy ngẫm về vị trí của bạn trong xã hội.", reversed_description: "Khi Mannaz xuất hiện đảo ngược, ego thống trị và cô lập tăng lên. Rune này cảnh báo về tự lợi, tách rời từ cộng đồng hoặc yếu đuối nội tâm. Nó gọi bạn kết nối lại với người khác và kiểm tra ego của bạn.", upright_guidance: "Tự nhận thức - Hiểu bản thân. Cộng đồng - Kết nối được tôn trọng. Tiềm năng - Hiện thực hóa nó.", reversed_guidance: "Tự lợi - Ego thống trị. Yếu đuối - Sự mong manh bộc lộ. Cô lập - Kết nối lại." },
  { id: 21, name: "Laguz", symbol: "ᛚ", meaning: "Nước, chảy, cảm xúc", reversed: "Tình trạng đông cứng, hỗn loạn cảm xúc", description: "Laguz đại diện cho nước, cảm xúc và dòng chảy của cuộc sống. Nó biểu tượng cho trực giác, chữa lành và tâm trí tiềm ẩn. Rune này thường chỉ ra nhu cầu tin tưởng trực giác của bạn, chữa lành cảm xúc hoặc cho phép cuộc sống chảy tự nhiên.", reversed_description: "Khi Laguz xuất hiện đảo ngược, các dòng chảy cảm xúc trở nên động dậy và trực giác thất bại. Rune này cảnh báo về hỗn loạn nội tâm, trực giác bị chặn hoặc tình trạng đông cứng trong dòng chảy cảm xúc của bạn. Nó gọi bạn tìm kiếm sự rõ ràng và cho phép các cảm xúc lắng xuống.", upright_guidance: "Nước chảy - Cảm xúc rõ ràng. Trực giác - Tin tưởng nó. Chữa lành - Bắt đầu tự nhiên.", reversed_guidance: "Tình trạng đông cứng - Dòng chảy bị chặn. Hỗn loạn - Cảm xúc hỗn loạn. Trực giác - Bối rối." },
  { id: 22, name: "Ingwaz", symbol: "ᛝ", meaning: "Ing, sinh sản, khởi đầu mới", reversed: "Tình trạng đông cứng, thiếu tiến bộ", description: "Ingwaz là rune của vị thần Ing, đại diện cho sinh sản, hoàn thành và khởi đầu mới. Nó biểu tượng cho hạt giống của tiềm năng và chuyển đổi. Rune này thường chỉ ra rằng các dự án đang tiến tới hoàn thành hoặc các vụ kinh doanh mới sắp bắt đầu.", reversed_description: "Khi Ingwaz xuất hiện đảo ngược, các dự án tạm dừng và khởi đầu mới bị trễ. Rune này cảnh báo về tình trạng không hoàn thành, vô sinh ý tưởng hoặc không thể tiến lên. Nó gọi bạn loại bỏ các cơn tắc và tìm những gì sẽ khởi động lại động lực của bạn.", upright_guidance: "Sinh sản - Cuộc sống mới. Hoàn thành - Đóng cửa gần. Bắt đầu - Khởi động tươi.", reversed_guidance: "Tình trạng đông cứng - Tiến bộ bị dính. Vô sinh - Cảm thấy vô sinh. Không hoàn thành - Chưa kết thúc." },
  { id: 23, name: "Othala", symbol: "ᛟ", meaning: "Di sản, nhà, tài sản", reversed: "Mất mát, xa nhà", description: "Othala đại diện cho di sản, nhà và tài sản gia tộc. Nó biểu tượng cho an ninh, gia đình và vị trí của bạn trên thế giới. Rune này thường chỉ ra ổn định, kết nối gia đình hoặc sự hiện thực hóa của cảm giác thuộc về và an ninh.", reversed_description: "Khi Othala xuất hiện đảo ngược, ổn định sụp đổ và xa nhà đe dọa. Rune này cảnh báo về mất mát nhà cửa, bất hòa gia đình hoặc mất an ninh. Nó gọi bạn tìm kiếm nơi trú ẩn và tái xây dựng nền tảng của bạn.", upright_guidance: "Nhà an toàn - Nền tảng chắc chắn. Di sản - Di sản được tôn trọng. Thuộc về - Bạn có rễ.", reversed_guidance: "Mất mát sắp tới - Bất an cảm thấy. Xa nhà - Bị uốn tròn. Vô gia cư - Tìm kiếm nơi." },
  { id: 24, name: "Dagaz", symbol: "ᛞ", meaning: "Ngày, đột phá, sự rõ ràng", reversed: "Nhầm lẫn, tình trạng đông cứng", description: "Dagaz đại diện cho ngày và đột phá. Nó biểu tượng cho sự rõ ràng, đột phá và chiến thắng của ánh sáng. Rune này thường chỉ ra sự rõ ràng đột ngột, đột phá trong sự hiểu biết hoặc sự nổi lên của một ngày mới mang lại thay đổi tích cực.", reversed_description: "Khi Dagaz xuất hiện đảo ngược, đột phá bị trễ và nhầm lẫn tồn tại. Rune này cảnh báo về bóng tối tiếp tục, không thể nhìn thấy rõ ràng hoặc tình trạng đông cứng bền bỉ. Nó gọi bạn có kiên nhẫn khi bạn chờ đợi ánh sáng quay trở lại.", upright_guidance: "Đột phá - Sự rõ ràng đến. Ngày bình minh - Ánh sáng mới. Chuyển đổi - Sự dịch chuyển đột ngột.", reversed_guidance: "Nhầm lẫn - Sự rõ ràng trốn. Tình trạng đông cứng - Đột phá trễ. Bóng tối - Kéo dài." }
]

export const QUESTION_CONTEXTS_VI = {
  love: {
    title: "Tình yêu & Mối quan hệ",
    interpretation: "Bài đọc này khám phá các vấn đề về trái tim, tình yêu lãng mạn và các mối quan hệ cá nhân."
  },
  career: {
    title: "Sự nghiệp & Công việc",
    interpretation: "Bài đọc này cung cấp thông tin chi tiết về con đường sự nghiệp và tình hình công việc của bạn."
  },
  health: {
    title: "Sức khỏe & Wellness",
    interpretation: "Bài đọc này giải quyết sức khỏe thể chất và tinh thần của bạn."
  },
  finance: {
    title: "Tài chính & Giàu có",
    interpretation: "Bài đọc này khám phá tình hình tài chính và sự thịnh vượng vật chất của bạn."
  },
  personal: {
    title: "Phát triển Cá nhân",
    interpretation: "Bài đọc này tập trung vào phát triển bản thân và chuyển đổi cá nhân."
  },
  general: {
    title: "Hướng dẫn Chung",
    interpretation: "Bài đọc này cung cấp thông tin chi tiết và hướng dẫn chung về tình hình hiện tại của bạn."
  }
}
